[phases.setup]
nixPkgs = ['nodejs_22', 'bun']

[phases.install]
cmds = ['bun install --frozen-lockfile']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'npx prisma db push --accept-data-loss && bun run start:prod'
